# SportConnect - Conexion MySQL Docker en AWS EC2
# IP elastica / fija actual: 34.206.126.154
# Contenedor esperado: sportconnect_mysql
# Puerto Docker publicado: 0.0.0.0:3306->3306/tcp

# IMPORTANTE: este archivo es el que realmente usa Java al arrancar.
# Si cambias la IP elastica de AWS, cambia db.host aqui.
db.host=34.206.126.154
db.port=3306
db.database=sportconnect
db.user=sportconnect_user
db.password=Sport1234!
